
__include__: [
  '../dataset/align_flir_X_ir_detection.yml',
  '../runtime.yml',
  './include/dataloader_X.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_X.yml',
]


output_dir: ./output/gmdetr_r18vd_6x_FLIRv1_X

checkpoint_step: 2

train_dataloader: 
  batch_size: 8
  num_workers: 8

PResNetX:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True

EfficientFusionEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

