__include__: [
  '../dataset/align_flir_X_ir_detection_train2.yml',
  '../runtime.yml',
  './include/dataloader_X.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_X.yml',
]

train_dataloader: 
  batch_size: 6
  num_workers: 6

optimizer:
  lr: 0.00005

output_dir: ./output/gmdetr_r50vd_6x_align_flir_X_train2


