__include__: [
  '../dataset/flir_custom_train1.yml',
  '../runtime.yml',
  './include/dataloader_X.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd_X.yml',
]

train_dataloader: 
  batch_size: 6
  num_workers: 6


output_dir: /home/data4/lzr/MM-DETR-OUTPUT-MALLOSS/output_stage1 # /home/data4/lzr/MM-DETR-OUTPUT/torch_output_stage1 

# stage1 使用 MAL 分类损失，如果使用VFL，改两个地方mal->vfl即可，True->False
SetCriterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2}
  losses: ['mal', 'boxes']
  use_mal: True
  mal_alpha: null
  mal_gamma: 1.5


