task: detection

model: RTDETRX
criterion: SetCriterion
postprocessor: RTDETRPostProcessor


RTDETRX:
  backbone: PPHGNetV2X6
  encoder: EfficientFusionEncoder
  decoder: RTDETRTransformer
  multi_scale: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]

PPHGNetV2X6:
  arch: 'X'
  use_lab: False
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

EfficientFusionEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  hidden_dim: 384
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 2048
  dropout: 0.0
  enc_act: 'gelu'
  pe_temperature: 10000

  expansion: 1.0
  depth_mult: 1.0
  act: 'silu'

  eval_spatial_size: [640, 640]


RTDETRTransformer:
  feat_channels: [384, 384, 384]
  feat_strides: [8, 16, 32]
  hidden_dim: 384
  num_levels: 3

  num_queries: 300
  num_decoder_layers: 6
  num_denoising: 100
  learnt_init_query: True
  learnable_query_ratio: 0.1

  eval_idx: -1
  eval_spatial_size: [640, 640]


use_focal_loss: True

RTDETRPostProcessor:
  num_top_queries: 300


SetCriterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2}
  losses: ['mal', 'boxes']
  alpha: 0.75
  gamma: 2.0
  use_mal: True
  mal_alpha: null
  mal_gamma: 1.5

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0
